### ISSUE TITLE
batch queuing

### ISSUE THREAD

**Issue by pthall** [pthall/SwaCheckin#3]
This would further enhance #1 

As an alternative to using script parameters for confirmation number, etc - add a parameter defining a YAML file path to load check-in parameters from. The file can contain one or more itineraries.

Possible new parameter `-f itineraries.yml`

Possible YAML structure
```
- itinerary:
  firstname: Shangela
  lastname: Wadley
  confirmation: ABC123
  email: shangela@wadley.example.com

- itinerary:
  firstname: Latrice
  lastname: Royale
  confirmation: ABC321
  email: latrice@royale.example.com
```
